nodeLinker: hoisted

packages:
  - "packages/*"
  - "packages/e2e/fixtures/*"
overrides:
  react: ^19.2.4
  react-dom: ^19.2.4
  vite: "catalog:"
  vitest: "catalog:"
patchedDependencies:
  react-devtools-core@7.0.1: patches/react-devtools-core@7.0.1.patch
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.16f3018f31dd475daf775e87e3eeb870fe9e5b4d
  vitest: 4.1.10
  vite-plus: 0.0.0-commit.16f3018f31dd475daf775e87e3eeb870fe9e5b4d
  "@vitest/coverage-istanbul": 4.1.10
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
