nodeLinker: hoisted

packages:
  - "packages/*"
  - "packages/conformance/fixtures/*"
  - "packages/e2e/fixtures/*"
overrides:
  react: ^19.3.0
  react-dom: ^19.3.0
  vite@*: "catalog:"
  vitest@*: "catalog:"
patchedDependencies:
  react-devtools-core@8.0.0: patches/react-devtools-core@8.0.0.patch
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.73ce44ef507f7c2aed23bc5addd747d0e3d0b33a
  vitest: 5.0.1
  vite-plus: 0.0.0-commit.73ce44ef507f7c2aed23bc5addd747d0e3d0b33a
  "@vitest/coverage-istanbul": 5.0.1
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
